Dotfiles cleaned up and properly integrated.

diff --git a/dotfiles/pgn_manage_alias b/dotfiles/pgn_manage_alias
--- a/dotfiles/pgn_manage_alias
+++ b/dotfiles/pgn_manage_alias
@@ -2,38 +2,45 @@
 # Functions
 #
 pgnm_checkenv() {
-    if [ "${PGN_MANAGE_SOURCE_PATH}" == "" ]; then
-        >&2 echo PGN-MANAGE error: PGN_MANAGE_SOURCE_PATH is not set. 
+    if [[ -v "${PGN_MANAGE_SOURCE_PATH}" ]]; then
+        echo 'PGN-MANAGE error: PGN_MANAGE_SOURCE_PATH is not set.' > /dev/stderr
+        return 255
+    elif [[ -z "${PGN_MANAGE_SOURCE_PATH}" ]]; then
+        echo 'PGN-MANAGE error: PGN_MANAGE_SOURCE_PATH is empty.' > /dev/stderr
         return 255
     fi
 
-    if [ "${PGN_MANAGE_DOWNLOADS_PATH}" == "" ]; then
-        >&2 echo PGN-MANAGE error: PGN_MANAGE_DOWNLOADS_PATH is not set. 
+    if [[ -v "${PGN_MANAGE_DOWNLOADS_PATH}" ]]; then
+        echo 'PGN-MANAGE error: PGN_MANAGE_DOWNLOADS_PATH is not set.' > /dev/stderr
+        return 255
+    elif [[ -z "${PGN_MANAGE_DOWNLOADS_PATH}" ]]; then
+        echo 'PGN-MANAGE error: PGN_MANAGE_DOWNLOADS_PATH is empty.' > /dev/stderr
         return 255
     fi
 
-    if [ "${PGN_MANAGE_USERNAME}" == "" ]; then
-        >&2 echo PGN-MANAGE error: PGN_MANAGE_USERNAME is not set. 
+    if [[ -v "${PGN_MANAGE_USERNAME}" ]]; then
+        echo 'PGN-MANAGE error: PGN_MANAGE_USERNAME is not set.' > /dev/stderr
+        return 255
+    elif [[ -z "${PGN_MANAGE_USERNAME}" ]]; then
+        echo 'PGN-MANAGE error: PGN_MANAGE_USERNAME is empty.' > /dev/stderr
         return 255
     fi
 }
 
 pgnm_exec() {
-    pgnm_checkenv
-    if [ $? -eq 0 ] ; then
-        # Do the thing
-        pushd $PGN_MANAGE_SOURCE_PATH > /dev/null
-        pipenv run python ./pgn-manage/pgn_manage.py $* > /dev/null &
-        popd > /dev/null
+    if pgnm_checkenv; then
+        pushd "$PGN_MANAGE_SOURCE_PATH" > /dev/null || exit
+        pipenv run python ./pgn_manage.py "$@"
+        popd > /dev/null || exit
     fi
 }
 
 pgnm_download() {
-    pgnm_exec download --user $PGN_MANAGE_USERNAME --output PGN_MANAGE_DOWNLOADS_PATH --source all
+    pgnm_exec download --user "$PGN_MANAGE_USERNAME" --output "$PGN_MANAGE_DOWNLOADS_PATH" --source all
 }
 
 #
 # Aliases
 #
 
-alias chessdl="pgnm_checkenv $*"
+lias chessdl="pgnm_download"
